exclude: ['readme.md']
name: "Nate Neff"
highlighter: pygments
github_username: nathanneff
twitter_username: nateneff
email: nate@nateneff.com
markdown: redcarpet
redcarpet:
        extensions: [ tables, autolink ]


